# Generated by Django 3.1.6 on 2021-02-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='profiles.Image'),
        ),
    ]
